CREATE TABLE EMPLOYEE (
    E_ID VARCHAR2(10) NOT NULL ENABLE,
    E_NAME VARCHAR2(40),
    ADDRESS VARCHAR2(40),
    MOBILE NUMBER(10,0),
    SALARY NUMBER(8,2),
    GENDER VARCHAR2(10),
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (E_ID) ENABLE
);

CREATE TABLE CUSTOMER (
    C_ID VARCHAR2(10) NOT NULL ENABLE,
    C_NAME VARCHAR2(40),
    ADDRESS VARCHAR2(40),
    MOBILE NUMBER,
    EMAIL VARCHAR2(40),
    GENDER VARCHAR2(10),
    E_ID VARCHAR2(10),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (C_ID) ENABLE,
    CONSTRAINT CUSTOMER_CK1 CHECK (GENDER IN ('male', 'female')) ENABLE,
    CONSTRAINT CUSTOMER_CON FOREIGN KEY (E_ID) REFERENCES EMPLOYEE (E_ID) ENABLE
);

CREATE TABLE BRANCH (
    BR_ID VARCHAR2(10) NOT NULL ENABLE,
    BR_NAME VARCHAR2(40),
    LOCATION VARCHAR2(40),
    ENUMBER NUMBER(10,0),
    CONSTRAINT BRANCH_PK PRIMARY KEY (BR_ID) ENABLE
);

CREATE TABLE PAYMENT (
    P_ID VARCHAR2(10) NOT NULL ENABLE,
    C_ID VARCHAR2(10),
    P_DATE DATE,
    AMOUNT NUMBER(8,2) NOT NULL ENABLE,
    CONSTRAINT PAYMENT_PK PRIMARY KEY (P_ID) ENABLE,
    CONSTRAINT PAYMENT_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMER (C_ID) ENABLE
);

CREATE TABLE BOOKING (
    B_ID VARCHAR2(10) NOT NULL ENABLE,
    TICKET VARCHAR2(40),
    N_PERSON NUMBER(8,0),
    CONSTRAINT BOOKING_PK PRIMARY KEY (B_ID) ENABLE
);

CREATE TABLE OWN (
    BR_ID VARCHAR2(10),
    E_ID VARCHAR2(10),
    CONSTRAINT OWN_FK FOREIGN KEY (BR_ID) REFERENCES BRANCH (BR_ID) ENABLE,
    CONSTRAINT OWN_FK2 FOREIGN KEY (E_ID) REFERENCES EMPLOYEE (E_ID) ENABLE
);

CREATE TABLE CHOOSE (
    C_ID VARCHAR2(10),
    H_ID VARCHAR2(10),
    CONSTRAINT CHOOSE_FK FOREIGN KEY (C_ID) REFERENCES CUSTOMER (C_ID) ENABLE,
    CONSTRAINT CHOOSE_FK2 FOREIGN KEY (H_ID) REFERENCES HOTEL (H_ID) ENABLE
);

CREATE TABLE MANAGE (
    E_ID VARCHAR2(10),
    C_ID VARCHAR2(10),
    P_ID VARCHAR2(10),
    B_ID VARCHAR2(10),
    CONSTRAINT MANAGE_FK FOREIGN KEY (E_ID) REFERENCES EMPLOYEE (E_ID) ENABLE,
    CONSTRAINT MANAGE_FK2 FOREIGN KEY (C_ID) REFERENCES CUSTOMER (C_ID) ENABLE,
    CONSTRAINT MANAGE_FK3 FOREIGN KEY (P_ID) REFERENCES PAYMENT (P_ID) ENABLE,
    CONSTRAINT MANAGE_FK4 FOREIGN KEY (B_ID) REFERENCES BOOKING (B_ID) ENABLE
);

CREATE TABLE PROVIDE (
    B_ID VARCHAR2(10),
    H_ID VARCHAR2(10),
    V_ID VARCHAR2(10),
    B_DATE DATE,
    CONSTRAINT PROVIDE_FK FOREIGN KEY (B_ID) REFERENCES BOOKING (B_ID) ENABLE,
    CONSTRAINT PROVIDE_FK2 FOREIGN KEY (H_ID) REFERENCES HOTEL (H_ID) ENABLE,
    CONSTRAINT PROVIDE_FK3 FOREIGN KEY (V_ID) REFERENCES VEHICLE (V_ID) ENABLE
);

CREATE TABLE HOTEL (
    H_ID VARCHAR2(10) NOT NULL ENABLE,
    H_NAME VARCHAR2(40),
    H_ADDRESS VARCHAR2(40),
    CONSTRAINT HOTEL_PK PRIMARY KEY (H_ID) ENABLE
);

CREATE TABLE VEHICLE (
    V_ID VARCHAR2(10) NOT NULL ENABLE,
    V_TYPE VARCHAR2(10),
    LICENCE_NUM VARCHAR2(10),
    CONSTRAINT VEHICLE_PK PRIMARY KEY (V_ID) ENABLE
);
